### ISSUE TITLE
NullReference for no reason.

### ISSUE THREAD

**Issue by J0nathan550** [dead8309/KizzyRPC#6] opened 2022-08-01 20:27 UTC
Tried to make simple android application, where you press on play button. And it should enable RPC.
That button contain hardcoded information off my presence, Token, Details, App name, state... 
And when I test my application on phone I get null reference exception. 
I followed all instructions that you set on "README" file. But still get error. Can you help on solving problem?
```java
public void onClick(View view) {
                try {
                    KizzyRPCservice rpc = new KizzyRPCservice("secret");
                    check = !check;
                    if (check) {
                        startButton.setText("End");
                        rpc.setName("Test RPC")
                                .setDetails("Test Detail")
                                .setLargeImage("attachments/947494021360656434/994352053876949092/DedSec.png")
                                .setSmallImage("attachments/947494021360656434/994352053876949092/DedSec.png")
                                .setState("Test State")
                                .setType(0)
                                .setStartTimestamps(System.currentTimeMillis())
                                .setButton1("Github Profile", "https://github.com/J0nathan550")
                                .setButton2("YouTube", "https://www.youtube.com")
                                .build();
                    } else {
                        startButton.setText("Start");
                        rpc.closeRPC();
                    }
                }
                catch (Exception e){
                    System.out.println(e.getMessage());
                }
            }
        });
```

**Comment by dead8309** [comment] 2022-08-01 20:30
Could you send the log details here

**Comment by J0nathan550** [comment] 2022-08-01 20:34
```
E/AndroidRuntime: FATAL EXCEPTION: WebSocketConnectReadThread-729
    Process: com.j0nathan550.discordrpc, PID: 20248
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Thread.isInterrupted()' on a null object reference
        at com.my.kizzyrpc.KizzyRPCservice.closeRPC(KizzyRPCservice.java:56)
        at com.my.kizzyrpc.KizzyRPCservice$1.onError(KizzyRPCservice.java:376)
        at org.java_websocket.client.WebSocketClient.onWebsocketError(WebSocketClient.java:673)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:493)
```

**Comment by J0nathan550** [comment] 2022-08-01 20:35
Do you think buttons could be a problem? When I used your application even there I get null reference.

**Comment by dead8309** [comment] 2022-08-01 20:41
> Do you think buttons could be a problem? When I used your application even there I get null reference.

No , the problem is arising because you are closing the RPC connection too early. try to wait for few seconds

**Comment by J0nathan550** [comment] 2022-08-01 20:44
But, when I want to connect it crash me. Can you send example onto how to "wait"?

**Comment by dead8309** [comment] 2022-08-01 20:48
Fixed the null issue in latest  [commit](https://github.com/dead8309/KizzyRPC/commit/0297840140bd8ba4291d2a658b72875297a3a592) .

**Comment by J0nathan550** [comment] 2022-08-01 20:50
How can I update code?

**Comment by J0nathan550** [comment] 2022-08-01 20:50
Nevermind, let me try!

**Comment by dead8309** [comment] 2022-08-01 20:54
> How can I update code?

Just update the Dependency version to 1.0.4

**Comment by J0nathan550** [comment] 2022-08-01 21:10
Well some progress! Now I don't get any nullreference exception, But I don't see any custom status at my profile 😄.
Debug says that I'm connecting, and that's it. Is there anymore requirements I need in my application?
Or can you say on what should I make sure first?
Also token. I should get it from login? Or token of some application?

**Comment by dead8309** [comment] 2022-08-01 21:12
> Well some progress! Now I don't get any nullreference exception, But I don't see any custom status at my profile 😄. Debug says that I'm connecting, and that's it. Is there anymore requirements I need in my application? Or can you say on what should I make sure first? Also token. I should get it from login? Or token of some application?

Make sure you have internet permission in manifest

**Comment by J0nathan550** [comment] 2022-08-01 21:38
Added, but still. No luck. Maybe I should somehow make it run on background?

**Comment by dead8309** [comment] 2022-08-01 21:40
Check the sample app source.

**Comment by J0nathan550** [comment] 2022-08-01 21:48
```java
E/Connection opened: 
W/System.err: java.lang.InterruptedException
W/System.err:     at java.lang.Thread.sleep(Native Method)
W/System.err:     at java.lang.Thread.sleep(Thread.java:373)
W/System.err:     at java.lang.Thread.sleep(Thread.java:314)
W/System.err:     at com.my.kizzyrpc.KizzyRPCservice.lambda$new$0$com-my-kizzyrpc-KizzyRPCservice(KizzyRPCservice.java:47)
W/System.err:     at com.my.kizzyrpc.KizzyRPCservice$$ExternalSyntheticLambda0.run(Unknown Source:2
```
Here comes new error. Progress!

**Comment by dead8309** [comment] 2022-08-02 04:39
> ```java
> E/Connection opened: 
> W/System.err: java.lang.InterruptedException
> W/System.err:     at java.lang.Thread.sleep(Native Method)
> W/System.err:     at java.lang.Thread.sleep(Thread.java:373)
> W/System.err:     at java.lang.Thread.sleep(Thread.java:314)
> W/System.err:     at com.my.kizzyrpc.KizzyRPCservice.lambda$new$0$com-my-kizzyrpc-KizzyRPCservice(KizzyRPCservice.java:47)
> W/System.err:     at com.my.kizzyrpc.KizzyRPCservice$$ExternalSyntheticLambda0.run(Unknown Source:2
> ```
> 
> Here comes new error. Progress!

That's not an error it is just the log of the thread which is stopped .It doesn't crash the application

**Comment by J0nathan550** [comment] 2022-08-02 08:41
But what to do in this case?

**Comment by dead8309** [comment] 2022-08-02 08:45
Nothing

**Closed** 2022-08-05 16:15 UTC
Labels: bug
